-----------------DB2版本--------------------
----ALLOW REVERSE SCANS：允许双向扫描
----COLLECT SAMPLED DETAILED STATISTICS：考虑在创建索引时收集统计信息，可以加快统计信息的收集，还可以指采样。
----
---1、登记中心
CREATE INDEX IDX_RGCTHIST_ACCTNO_BANKNO ON TRGCT_BILL_HIST (HOLD_ACCT_NO ASC, 
HOLD_BANK_NO ASC, IS_LOCK ASC, CUR_STATUS ASC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED 
STATISTICS;

CREATE INDEX IDX_RGCTINFO_CLASS_TYPE ON TRGCT_BILL_INFO 
   (BILL_CLASS  ASC, DEL_FLAG ASC, BILL_TYPE ASC,
   DUE_DT ASC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;
   
-----2、贴现
CREATE INDEX IDX_DISCBILL_DISCID_OPSTA ON TDISC_BILL_INFO
   (DISC_ID ASC, OPER_STATUS ASC, CUST_NO ASC,
   CUST_ACCOUNT ASC, BRANCH_NO ASC, DISCMX_ID DESC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;
   
CREATE INDEX IDX_DISCBILL_OPERSTATUS_NO ON TDISC_BILL_INFO
   (OPER_STATUS ASC, BRANCH_NO ASC, BILL_CLASS
   ASC, DISC_ID ASC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;
   
CREATE INDEX IDX_DISCBILL_DISCID_BRANCHNO ON TDISC_BILL_INFO
   (DISC_ID ASC, OPER_STATUS ASC, BRANCH_NO ASC,
   DISCMX_ID DESC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;

CREATE INDEX IDX_DISCBILL_STATUS_TYPE ON TDISC_BILL_INFO
   (OPER_STATUS ASC, RATE ASC, ORG_CODE ASC, OPER_BANK_NO
   ASC, DISC_DT ASC, BILL_CLASS ASC, BILL_TYPE
   ASC, DISCMX_ID DESC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;

CREATE INDEX IDX_DISCBILL_STATUS_CLASS ON TDISC_BILL_INFO
   (OPER_STATUS ASC, APPLY_OPER_NO ASC, BRANCH_NO ASC, BILL_CLASS ASC, DISC_ID ASC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;

CREATE INDEX IDX_DISCBILL_AUDITOPERNO_CLASS ON TDISC_BILL_INFO
   (OPER_STATUS ASC, AUDIT_OPER_NO ASC, BRANCH_NO
   ASC, BILL_CLASS ASC, DISC_ID ASC) ALLOW REVERSE
   SCANS COLLECT SAMPLED DETAILED STATISTICS;
   
-----3、转卖
CREATE INDEX IDX_SALE_CLASS_BRCH_STS ON tsale_apply_info
   (bill_Class ASC, bill_Storage_Brchno ASC, apply_Status
   ASC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;
 
CREATE INDEX IDX_SALEBILL_APPLYID ON  tsale_bill_info(sale_id ASC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;

CREATE INDEX IDX_SALE_CLASS_BRCH_STS ON TSALE_APPLY_INFO ( BILL_CLASS ASC, BILL_STORAGE_BRCHNO ASC, APPLY_STATUS ASC)ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;

-----4、承兑
CREATE INDEX IDX_ACPTAPPLYBILL_STATUS_NO ON TACPT_BILL_INFO 
   (STATUS ASC, BILL_CLASS ASC, BRANCH_NO
   ASC, BILL_STATUS ASC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;
   
CREATE INDEX IDX_ACPTAPPLY_CLASS_BRANCHNO ON TACPT_APPLY_INFO (BILL_CLASS ASC,BRANCH_NO ASC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;
   
CREATE INDEX IDX_ACPTBILL_APPLYID ON  tacpt_bill_info(acpt_id ASC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;  

-----5、发托
CREATE INDEX IDX_SUBCOLLBILL_STATUS_OPERNO ON TSUBCOLL_BILL_INFO
   (OPER_STATUS ASC, OPER_NO ASC, SUBCOLL_ID ASC)
   ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;
   
CREATE INDEX IDX_SUBCOLLBILL_APPLYID ON  tsubcoll_BILL_info(subcoll_id ASC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;
   
   
   
--------------ORACLE版本------------------ 
----------可选参数-------
----pctfree 10 --块保留10%的空间留给更新该块数据使用
----initrans 1 --初始化事务槽的个数
----maxtrans 255 --最大事务槽的个数
----storage --存储参数
----( 
----initial 64k --区段(extent)一次扩展64k
----minextents 1 --最小区段数
----maxextents unlimited --最大区段无限制 
----); 
----
-------1、登记中心rgct
CREATE INDEX IDX_RGCTHIST_ACCTNO_BANKNO ON TRGCT_BILL_HIST
   (HOLD_ACCT_NO ASC, HOLD_BANK_NO ASC, IS_LOCK
   ASC, CUR_STATUS ASC) TABLESPACE CBSPIDX 

CREATE INDEX IDX_RGCTINFO_CLASS_TYPE ON TRGCT_BILL_INFO 
   (BILL_CLASS  ASC, DEL_FLAG ASC, BILL_TYPE ASC,
   DUE_DT ASC) TABLESPACE CBSPIDX
   
-------2、贴现
CREATE INDEX IDX_DISCBILL_DISCID_OPSTA ON TDISC_BILL_INFO
   (DISC_ID ASC, OPER_STATUS ASC, CUST_NO ASC,
   CUST_ACCOUNT ASC, BRANCH_NO ASC, DISCMX_ID DESC) TABLESPACE CBSPIDX
   
CREATE INDEX IDX_DISCBILL_OPERSTATUS_NO ON TDISC_BILL_INFO
   (OPER_STATUS ASC, BRANCH_NO ASC, BILL_CLASS
   ASC, DISC_ID ASC) TABLESPACE CBSPIDX;
   
CREATE INDEX IDX_DISCBILL_DISCID_BRANCHNO ON TDISC_BILL_INFO
   (DISC_ID ASC, OPER_STATUS ASC, BRANCH_NO ASC,
   DISCMX_ID DESC) TABLESPACE CBSPIDX
   
CREATE INDEX IDX_DISCBILL_STATUS_TYPE ON TDISC_BILL_INFO
   (OPER_STATUS ASC, RATE ASC, ORG_CODE ASC, OPER_BANK_NO
   ASC, DISC_DT ASC, BILL_CLASS ASC, BILL_TYPE
   ASC, DISCMX_ID DESC) TABLESPACE CBSPIDX

CREATE INDEX IDX_DISCBILL_STATUS_CLASS ON TDISC_BILL_INFO
   (OPER_STATUS ASC, APPLY_OPER_NO ASC, BRANCH_NO
   ASC, BILL_CLASS ASC, DISC_ID ASC) TABLESPACE CBSPIDX

CREATE INDEX IDX_DISCBILL_AUDITOPERNO_CLASS ON TDISC_BILL_INFO
   (OPER_STATUS ASC, AUDIT_OPER_NO ASC, BRANCH_NO
   ASC, BILL_CLASS ASC, DISC_ID ASC) TABLESPACE CBSPIDX
   
-------3、转卖
 CREATE INDEX IDX_SALE_CLASS_BRCH_STS ON tsale_apply_info
   (bill_Class ASC, bill_Storage_Brchno ASC, apply_Status
   ASC) TABLESPACE CBSPIDX; 
 
CREATE INDEX IDX_SALEBILL_APPLYID ON  tsale_bill_info(sale_id ASC)TABLESPACE CBSPIDX;

CREATE INDEX IDX_SALE_CLASS_BRCH_STS ON TSALE_APPLY_INFO ( BILL_CLASS ASC, BILL_STORAGE_BRCHNO ASC, APPLY_STATUS ASC)TABLESPACE CBSPIDX;
-------4、承兑
CREATE INDEX IDX_ACPTAPPLYBILL_STATUS_NO ON TACPT_BILL_INFO 
   (STATUS ASC, BILL_CLASS ASC, BRANCH_NO
   ASC, BILL_STATUS ASC) TABLESPACE CBSPIDX;
   
CREATE INDEX IDX_ACPTAPPLY_CLASS_BRANCHNO ON TACPT_APPLY_INFO (BILL_CLASS ASC,BRANCH_NO ASC) TABLESPACE CBSPIDX;

CREATE INDEX IDX_ACPTBILL_APPLYID ON  tacpt_bill_info(acpt_id ASC)TABLESPACE CBSPIDX;  

-------5、发托
CREATE INDEX IDX_SUBCOLLBILL_STATUS_OPERNO ON TSUBCOLL_BILL_INFO
   (OPER_STATUS ASC, OPER_NO ASC, SUBCOLL_ID ASC)
   TABLESPACE CBSPIDX;
   
CREATE INDEX IDX_SUBCOLLBILL_APPLYID ON  tsubcoll_BILL_info(subcoll_id ASC)TABLESPACE CBSPIDX;


